export const PRODUCTS = [
  {
    id: 0,
    productId: 0,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Strawberry Cake",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: true,
    priceStart: "from $20",
    categories: "bakery",
    productUnit: ["small", "medium", "large"],
  },
  {
    id: 1,
    productId: 1,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Cheesecake pastry",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: true,
    priceStart: "from $8",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 2,
    productId: 2,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Macaron",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: true,
    priceStart: "from $2",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 3,
    productId: 3,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Mango Chutney",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: true,
    priceStart: "from $12",
    categories: "jams",
    productUnit: ["piece"],
  },
  {
    id: 4,
    productId: 4,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Lemon Pie",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $15",
    categories: "bakery",
    productUnit: ["small", "medium", "large"],
  },
  {
    id: 5,
    productId: 5,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Organic Jams",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $15",
    categories: "jams",
    productUnit: ["piece"],
  },

  {
    id: 6,
    productId: 6,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Heart Cookie",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $1.5",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 7,
    productId: 7,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Luxury cake",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $30",
    categories: "bakery",
    productUnit: ["small", "medium", "large"],
  },
  {
    id: 8,
    productId: 8,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Donuts sorted",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $1.75",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 9,
    productId: 9,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Chocolate Donut",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $1.75",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 10,
    productId: 10,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Cupcake Vanilla",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $2.50",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 11,
    productId: 11,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Cupcake Sprinkles",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $2.50",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 12,
    productId: 12,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Chocolate cookies",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $2.50",
    categories: "bakery",
    productUnit: ["piece", "half-dozen", "dozen"],
  },
  {
    id: 13,
    productId: 13,
    image:
      "https://res.cloudinary.com/marsmag/image/upload/v1598330344/sample.jpg",
    title: "Artisanal Bread",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    featured: false,
    priceStart: "from $15.50",
    categories: "bread",
    productUnit: ["piece"],
  },
];
